# Generated by Django 3.2.18 on 2023-04-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
